ktor:
    application:
        modules:
            - io.vladar107.ApplicationKt.module
    deployment:
        port: 8080

db:
    url: "jdbc:h2:file:./data/timematcher;DB_CLOSE_DELAY=-1"

calendar:
    provider: "inmemory"   # or "google"

google:
    clientId: ""
    clientSecret: ""
    refreshToken: ""
    calendarId: "primary"
