@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(host, "User", "Manage available time slots")
Person(attendee, "Attendee", "Meeting creator")

Container(adminBot, "Admin Bot", kotlin, "Admin Telegram Bot", robot)
Container(meetingBot, "Meeting Bot", kotlin, "Meeting Telegram Bot", robot)

Container_Ext(extCalendar, "External Calendar")

Container_Boundary(container, "",) {
Container(server, "Time Matcher App", kotlin, "Web Server")
ContainerDb(mainDb, "Main Storage", ????)
}

Rel_D(host, adminBot, telegram)
Rel_U(adminBot, host, telegram)
Rel(adminBot, server, REST)

Rel_D(attendee, meetingBot, telegram)
Rel_U(meetingBot, attendee, telegram)
Rel(meetingBot, server, REST)

Rel(server, extCalendar, REST)
Rel(server, mainDb, ??)

@enduml
