@startuml
entity "User" as user {
  *id: uuid <<generated>>
  --
  name: string
  email: string
  status: string
  created_at: datetime
  deleted_at: datetime
}

entity "Attendee" as attendee {
  *id: uuid <<generated>>
  --
  name: string
  email: string
  created_at: datetime
}

entity "Calendar" as calendar {
  *id: uuid <<generated>>
  --
  name: string
  type: string
  provider: string
  token: string
  user_id: uuid
  added_at: datetime
}

entity "EventType" as event_type {
  *id: uuid <<generated>>
  --
  name: string
  description: string
  status: string
  created_at: datetime
  deleted_at: datetime
  gap_before: integer
  gap_after: integer
  additional_questions: json
}

entity "Event" as event {
  *id: uuid <<generated>>
  --
  name: string
  description: string
  start_at: datetime
  end_at: datetime
  calendar_id: uuid
  event_type_id: uuid
  created_at: datetime
  cancelled_at: datetime
}

user ||--o{ calendar
user }o--o{ event
event ||--|| event_type
event ||--|| calendar
event }o--o{ attendee

@enduml
